imports:
- javascript
- php

filter:
  excluded_paths: [ext/*/lib/*,ext/tagger/script.js,tests/*]

build:
  image: default-bionic
  nodes:
    analysis:
      tests:
        before:
          - mkdir -p data/config
          - cp tests/defines.php data/config/shimmie.conf.php
        override:
          - php-scrutinizer-run

tools:
  external_code_coverage: true
